// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: friend.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	_ "trpc.group/trpc/trpc-protocol/pb/go/trpc/api"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUid         string                 `protobuf:"bytes,1,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	ApplyText     string                 `protobuf:"bytes,2,opt,name=apply_text,json=applyText,proto3" json:"apply_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFriendRequest) Reset() {
	*x = ApplyFriendRequest{}
	mi := &file_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFriendRequest) ProtoMessage() {}

func (x *ApplyFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFriendRequest.ProtoReflect.Descriptor instead.
func (*ApplyFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyFriendRequest) GetToUid() string {
	if x != nil {
		return x.ToUid
	}
	return ""
}

func (x *ApplyFriendRequest) GetApplyText() string {
	if x != nil {
		return x.ApplyText
	}
	return ""
}

type ApplyFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFriendResponse) Reset() {
	*x = ApplyFriendResponse{}
	mi := &file_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFriendResponse) ProtoMessage() {}

func (x *ApplyFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFriendResponse.ProtoReflect.Descriptor instead.
func (*ApplyFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyFriendResponse) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type AcceptFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequest) Reset() {
	*x = AcceptFriendRequest{}
	mi := &file_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequest) ProtoMessage() {}

func (x *AcceptFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptFriendRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type AcceptFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendResponse) Reset() {
	*x = AcceptFriendResponse{}
	mi := &file_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendResponse) ProtoMessage() {}

func (x *AcceptFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptFriendResponse) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

type RejectFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendRequest) Reset() {
	*x = RejectFriendRequest{}
	mi := &file_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendRequest) ProtoMessage() {}

func (x *RejectFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendRequest.ProtoReflect.Descriptor instead.
func (*RejectFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{4}
}

func (x *RejectFriendRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type RejectFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendResponse) Reset() {
	*x = RejectFriendResponse{}
	mi := &file_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendResponse) ProtoMessage() {}

func (x *RejectFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendResponse.ProtoReflect.Descriptor instead.
func (*RejectFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{5}
}

type DeleteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFriendRequest) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

type DeleteFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendResponse) Reset() {
	*x = DeleteFriendResponse{}
	mi := &file_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResponse) ProtoMessage() {}

func (x *DeleteFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResponse.ProtoReflect.Descriptor instead.
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{7}
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{8}
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*FriendInfo          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{9}
}

func (x *ListFriendsResponse) GetFriends() []*FriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"` // "received" or "sent"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{10}
}

func (x *ListRequestsRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestInfo   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{11}
}

func (x *ListRequestsResponse) GetRequests() []*FriendRequestInfo {
	if x != nil {
		return x.Requests
	}
	return nil
}

type FriendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	IsBlacklist   bool                   `protobuf:"varint,6,opt,name=is_blacklist,json=isBlacklist,proto3" json:"is_blacklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	mi := &file_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{12}
}

func (x *FriendInfo) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *FriendInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FriendInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FriendInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FriendInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendInfo) GetIsBlacklist() bool {
	if x != nil {
		return x.IsBlacklist
	}
	return false
}

type FriendRequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	SenderUid     string                 `protobuf:"bytes,2,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`
	SenderName    string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ApplyText     string                 `protobuf:"bytes,4,opt,name=apply_text,json=applyText,proto3" json:"apply_text,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestInfo) Reset() {
	*x = FriendRequestInfo{}
	mi := &file_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestInfo) ProtoMessage() {}

func (x *FriendRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestInfo.ProtoReflect.Descriptor instead.
func (*FriendRequestInfo) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{13}
}

func (x *FriendRequestInfo) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *FriendRequestInfo) GetSenderUid() string {
	if x != nil {
		return x.SenderUid
	}
	return ""
}

func (x *FriendRequestInfo) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *FriendRequestInfo) GetApplyText() string {
	if x != nil {
		return x.ApplyText
	}
	return ""
}

func (x *FriendRequestInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendRequestInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_friend_proto protoreflect.FileDescriptor

const file_friend_proto_rawDesc = "" +
	"\n" +
	"\ffriend.proto\x12\techat.api\x1a\x1atrpc/api/annotations.proto\"J\n" +
	"\x12ApplyFriendRequest\x12\x15\n" +
	"\x06to_uid\x18\x01 \x01(\tR\x05toUid\x12\x1d\n" +
	"\n" +
	"apply_text\x18\x02 \x01(\tR\tapplyText\",\n" +
	"\x13ApplyFriendResponse\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\",\n" +
	"\x13AcceptFriendRequest\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\"(\n" +
	"\x14AcceptFriendResponse\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\",\n" +
	"\x13RejectFriendRequest\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\"\x16\n" +
	"\x14RejectFriendResponse\"'\n" +
	"\x13DeleteFriendRequest\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\"\x16\n" +
	"\x14DeleteFriendResponse\"\x14\n" +
	"\x12ListFriendsRequest\"F\n" +
	"\x13ListFriendsResponse\x12/\n" +
	"\afriends\x18\x01 \x03(\v2\x15.echat.api.FriendInfoR\afriends\"3\n" +
	"\x13ListRequestsRequest\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\"P\n" +
	"\x14ListRequestsResponse\x128\n" +
	"\brequests\x18\x01 \x03(\v2\x1c.echat.api.FriendRequestInfoR\brequests\"\x9f\x01\n" +
	"\n" +
	"FriendInfo\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12!\n" +
	"\fis_blacklist\x18\x06 \x01(\bR\visBlacklist\"\xc2\x01\n" +
	"\x11FriendRequestInfo\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x02 \x01(\tR\tsenderUid\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x1d\n" +
	"\n" +
	"apply_text\x18\x04 \x01(\tR\tapplyText\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime2\xa4\x05\n" +
	"\rFriendService\x12k\n" +
	"\vApplyFriend\x12\x1d.echat.api.ApplyFriendRequest\x1a\x1e.echat.api.ApplyFriendResponse\"\x1d\xca\xc1\x18\x19:\x01*\"\x14/api/v1/friend/apply\x12o\n" +
	"\fAcceptFriend\x12\x1e.echat.api.AcceptFriendRequest\x1a\x1f.echat.api.AcceptFriendResponse\"\x1e\xca\xc1\x18\x1a:\x01*\"\x15/api/v1/friend/accept\x12o\n" +
	"\fRejectFriend\x12\x1e.echat.api.RejectFriendRequest\x1a\x1f.echat.api.RejectFriendResponse\"\x1e\xca\xc1\x18\x1a:\x01*\"\x15/api/v1/friend/reject\x12k\n" +
	"\fDeleteFriend\x12\x1e.echat.api.DeleteFriendRequest\x1a\x1f.echat.api.DeleteFriendResponse\"\x1a\xca\xc1\x18\x16*\x14/api/v1/friend/{fid}\x12g\n" +
	"\vListFriends\x12\x1d.echat.api.ListFriendsRequest\x1a\x1e.echat.api.ListFriendsResponse\"\x19\xca\xc1\x18\x15\x12\x13/api/v1/friend/list\x12n\n" +
	"\fListRequests\x12\x1e.echat.api.ListRequestsRequest\x1a\x1f.echat.api.ListRequestsResponse\"\x1d\xca\xc1\x18\x19\x12\x17/api/v1/friend/requestsB\x18Z\x16echat/service/api/stubb\x06proto3"

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData []byte
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)))
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_friend_proto_goTypes = []any{
	(*ApplyFriendRequest)(nil),   // 0: echat.api.ApplyFriendRequest
	(*ApplyFriendResponse)(nil),  // 1: echat.api.ApplyFriendResponse
	(*AcceptFriendRequest)(nil),  // 2: echat.api.AcceptFriendRequest
	(*AcceptFriendResponse)(nil), // 3: echat.api.AcceptFriendResponse
	(*RejectFriendRequest)(nil),  // 4: echat.api.RejectFriendRequest
	(*RejectFriendResponse)(nil), // 5: echat.api.RejectFriendResponse
	(*DeleteFriendRequest)(nil),  // 6: echat.api.DeleteFriendRequest
	(*DeleteFriendResponse)(nil), // 7: echat.api.DeleteFriendResponse
	(*ListFriendsRequest)(nil),   // 8: echat.api.ListFriendsRequest
	(*ListFriendsResponse)(nil),  // 9: echat.api.ListFriendsResponse
	(*ListRequestsRequest)(nil),  // 10: echat.api.ListRequestsRequest
	(*ListRequestsResponse)(nil), // 11: echat.api.ListRequestsResponse
	(*FriendInfo)(nil),           // 12: echat.api.FriendInfo
	(*FriendRequestInfo)(nil),    // 13: echat.api.FriendRequestInfo
}
var file_friend_proto_depIdxs = []int32{
	12, // 0: echat.api.ListFriendsResponse.friends:type_name -> echat.api.FriendInfo
	13, // 1: echat.api.ListRequestsResponse.requests:type_name -> echat.api.FriendRequestInfo
	0,  // 2: echat.api.FriendService.ApplyFriend:input_type -> echat.api.ApplyFriendRequest
	2,  // 3: echat.api.FriendService.AcceptFriend:input_type -> echat.api.AcceptFriendRequest
	4,  // 4: echat.api.FriendService.RejectFriend:input_type -> echat.api.RejectFriendRequest
	6,  // 5: echat.api.FriendService.DeleteFriend:input_type -> echat.api.DeleteFriendRequest
	8,  // 6: echat.api.FriendService.ListFriends:input_type -> echat.api.ListFriendsRequest
	10, // 7: echat.api.FriendService.ListRequests:input_type -> echat.api.ListRequestsRequest
	1,  // 8: echat.api.FriendService.ApplyFriend:output_type -> echat.api.ApplyFriendResponse
	3,  // 9: echat.api.FriendService.AcceptFriend:output_type -> echat.api.AcceptFriendResponse
	5,  // 10: echat.api.FriendService.RejectFriend:output_type -> echat.api.RejectFriendResponse
	7,  // 11: echat.api.FriendService.DeleteFriend:output_type -> echat.api.DeleteFriendResponse
	9,  // 12: echat.api.FriendService.ListFriends:output_type -> echat.api.ListFriendsResponse
	11, // 13: echat.api.FriendService.ListRequests:output_type -> echat.api.ListRequestsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
