// Code generated by MockGen. DO NOT EDIT.
// Source: user.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=user_mock.go -package=stub --source=user.trpc.go -self_package=echat/service/api/stub
//

// Package stub is a generated GoMock package.
package stub

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockUserServiceService is a mock of UserServiceService interface.
type MockUserServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceServiceMockRecorder
}

// MockUserServiceServiceMockRecorder is the mock recorder for MockUserServiceService.
type MockUserServiceServiceMockRecorder struct {
	mock *MockUserServiceService
}

// NewMockUserServiceService creates a new mock instance.
func NewMockUserServiceService(ctrl *gomock.Controller) *MockUserServiceService {
	mock := &MockUserServiceService{ctrl: ctrl}
	mock.recorder = &MockUserServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceService) EXPECT() *MockUserServiceServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockUserServiceService) ISGOMOCK() struct{} {
	return struct{}{}
}

// GetUserInfo mocks base method.
func (m *MockUserServiceService) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, req)
	ret0, _ := ret[0].(*GetUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockUserServiceServiceMockRecorder) GetUserInfo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockUserServiceService)(nil).GetUserInfo), ctx, req)
}

// Login mocks base method.
func (m *MockUserServiceService) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceServiceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserServiceService)(nil).Login), ctx, req)
}

// Register mocks base method.
func (m *MockUserServiceService) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceServiceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserServiceService)(nil).Register), ctx, req)
}

// MockUserServiceClientProxy is a mock of UserServiceClientProxy interface.
type MockUserServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceClientProxyMockRecorder
}

// MockUserServiceClientProxyMockRecorder is the mock recorder for MockUserServiceClientProxy.
type MockUserServiceClientProxyMockRecorder struct {
	mock *MockUserServiceClientProxy
}

// NewMockUserServiceClientProxy creates a new mock instance.
func NewMockUserServiceClientProxy(ctrl *gomock.Controller) *MockUserServiceClientProxy {
	mock := &MockUserServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockUserServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceClientProxy) EXPECT() *MockUserServiceClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockUserServiceClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// GetUserInfo mocks base method.
func (m *MockUserServiceClientProxy) GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...client.Option) (*GetUserInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInfo", varargs...)
	ret0, _ := ret[0].(*GetUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockUserServiceClientProxyMockRecorder) GetUserInfo(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockUserServiceClientProxy)(nil).GetUserInfo), varargs...)
}

// Login mocks base method.
func (m *MockUserServiceClientProxy) Login(ctx context.Context, req *LoginRequest, opts ...client.Option) (*LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Login", varargs...)
	ret0, _ := ret[0].(*LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceClientProxyMockRecorder) Login(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserServiceClientProxy)(nil).Login), varargs...)
}

// Register mocks base method.
func (m *MockUserServiceClientProxy) Register(ctx context.Context, req *RegisterRequest, opts ...client.Option) (*RegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(*RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceClientProxyMockRecorder) Register(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserServiceClientProxy)(nil).Register), varargs...)
}
