// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: service/controller/proto/controller.proto

package stub

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ControllerServiceService defines service.
type ControllerServiceService interface {
	// AuthCheck Token 校验（Gateway 建连时调用）
	AuthCheck(ctx context.Context, req *AuthCheckRequest) (*AuthCheckResponse, error)
	// RouteMessage 消息路由（Gateway 收到客户端消息后调用）
	RouteMessage(ctx context.Context, req *RouteMessageRequest) (*RouteMessageResponse, error)
	// UpdateStatus 在线状态变更（Gateway 感知到上下线时调用）
	UpdateStatus(ctx context.Context, req *UpdateStatusRequest) (*UpdateStatusResponse, error)
}

func ControllerServiceService_AuthCheck_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AuthCheckRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ControllerServiceService).AuthCheck(ctx, reqbody.(*AuthCheckRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ControllerServiceService_RouteMessage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RouteMessageRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ControllerServiceService).RouteMessage(ctx, reqbody.(*RouteMessageRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ControllerServiceService_UpdateStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateStatusRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ControllerServiceService).UpdateStatus(ctx, reqbody.(*UpdateStatusRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ControllerServiceServer_ServiceDesc descriptor for server.RegisterService.
var ControllerServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "echat.controller.ControllerService",
	HandlerType: ((*ControllerServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/echat.controller.ControllerService/AuthCheck",
			Func: ControllerServiceService_AuthCheck_Handler,
		},
		{
			Name: "/echat.controller.ControllerService/RouteMessage",
			Func: ControllerServiceService_RouteMessage_Handler,
		},
		{
			Name: "/echat.controller.ControllerService/UpdateStatus",
			Func: ControllerServiceService_UpdateStatus_Handler,
		},
	},
}

// RegisterControllerServiceService registers service.
func RegisterControllerServiceService(s server.Service, svr ControllerServiceService) {
	if err := s.Register(&ControllerServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ControllerService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedControllerService struct{}

// AuthCheck Token 校验（Gateway 建连时调用）
func (s *UnimplementedControllerService) AuthCheck(ctx context.Context, req *AuthCheckRequest) (*AuthCheckResponse, error) {
	return nil, errors.New("rpc AuthCheck of service ControllerService is not implemented")
}

// RouteMessage 消息路由（Gateway 收到客户端消息后调用）
func (s *UnimplementedControllerService) RouteMessage(ctx context.Context, req *RouteMessageRequest) (*RouteMessageResponse, error) {
	return nil, errors.New("rpc RouteMessage of service ControllerService is not implemented")
}

// UpdateStatus 在线状态变更（Gateway 感知到上下线时调用）
func (s *UnimplementedControllerService) UpdateStatus(ctx context.Context, req *UpdateStatusRequest) (*UpdateStatusResponse, error) {
	return nil, errors.New("rpc UpdateStatus of service ControllerService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ControllerServiceClientProxy defines service client proxy
type ControllerServiceClientProxy interface {
	// AuthCheck Token 校验（Gateway 建连时调用）
	AuthCheck(ctx context.Context, req *AuthCheckRequest, opts ...client.Option) (rsp *AuthCheckResponse, err error)
	// RouteMessage 消息路由（Gateway 收到客户端消息后调用）
	RouteMessage(ctx context.Context, req *RouteMessageRequest, opts ...client.Option) (rsp *RouteMessageResponse, err error)
	// UpdateStatus 在线状态变更（Gateway 感知到上下线时调用）
	UpdateStatus(ctx context.Context, req *UpdateStatusRequest, opts ...client.Option) (rsp *UpdateStatusResponse, err error)
}

type ControllerServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewControllerServiceClientProxy = func(opts ...client.Option) ControllerServiceClientProxy {
	return &ControllerServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ControllerServiceClientProxyImpl) AuthCheck(ctx context.Context, req *AuthCheckRequest, opts ...client.Option) (*AuthCheckResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/echat.controller.ControllerService/AuthCheck")
	msg.WithCalleeServiceName(ControllerServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ControllerService")
	msg.WithCalleeMethod("AuthCheck")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AuthCheckResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ControllerServiceClientProxyImpl) RouteMessage(ctx context.Context, req *RouteMessageRequest, opts ...client.Option) (*RouteMessageResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/echat.controller.ControllerService/RouteMessage")
	msg.WithCalleeServiceName(ControllerServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ControllerService")
	msg.WithCalleeMethod("RouteMessage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RouteMessageResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ControllerServiceClientProxyImpl) UpdateStatus(ctx context.Context, req *UpdateStatusRequest, opts ...client.Option) (*UpdateStatusResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/echat.controller.ControllerService/UpdateStatus")
	msg.WithCalleeServiceName(ControllerServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ControllerService")
	msg.WithCalleeMethod("UpdateStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateStatusResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
