// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: service/controller/proto/controller.proto

package stub

import (
	common "echat/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================
// AuthCheck
// ============================================================
type AuthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCheckRequest) Reset() {
	*x = AuthCheckRequest{}
	mi := &file_service_controller_proto_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCheckRequest) ProtoMessage() {}

func (x *AuthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_controller_proto_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCheckRequest.ProtoReflect.Descriptor instead.
func (*AuthCheckRequest) Descriptor() ([]byte, []int) {
	return file_service_controller_proto_controller_proto_rawDescGZIP(), []int{0}
}

func (x *AuthCheckRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCheckResponse) Reset() {
	*x = AuthCheckResponse{}
	mi := &file_service_controller_proto_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCheckResponse) ProtoMessage() {}

func (x *AuthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_controller_proto_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCheckResponse.ProtoReflect.Descriptor instead.
func (*AuthCheckResponse) Descriptor() ([]byte, []int) {
	return file_service_controller_proto_controller_proto_rawDescGZIP(), []int{1}
}

func (x *AuthCheckResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *AuthCheckResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthCheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ============================================================
// RouteMessage
// ============================================================
type RouteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 发送者
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // 接收者
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                           // 消息内容
	MsgId         string                 `protobuf:"bytes,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                  // 客户端生成的临时消息 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMessageRequest) Reset() {
	*x = RouteMessageRequest{}
	mi := &file_service_controller_proto_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMessageRequest) ProtoMessage() {}

func (x *RouteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_controller_proto_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMessageRequest.ProtoReflect.Descriptor instead.
func (*RouteMessageRequest) Descriptor() ([]byte, []int) {
	return file_service_controller_proto_controller_proto_rawDescGZIP(), []int{2}
}

func (x *RouteMessageRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *RouteMessageRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *RouteMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RouteMessageRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type RouteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                 // 服务端分配的消息 ID
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务端时间戳
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                            // 说明（成功原因或失败原因）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMessageResponse) Reset() {
	*x = RouteMessageResponse{}
	mi := &file_service_controller_proto_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMessageResponse) ProtoMessage() {}

func (x *RouteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_controller_proto_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMessageResponse.ProtoReflect.Descriptor instead.
func (*RouteMessageResponse) Descriptor() ([]byte, []int) {
	return file_service_controller_proto_controller_proto_rawDescGZIP(), []int{3}
}

func (x *RouteMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouteMessageResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RouteMessageResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *RouteMessageResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ============================================================
// UpdateStatus
// ============================================================
type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        common.OnlineStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=common.OnlineStatus" json:"status,omitempty"`
	GatewayId     string                 `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_service_controller_proto_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_controller_proto_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_controller_proto_controller_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() common.OnlineStatus {
	if x != nil {
		return x.Status
	}
	return common.OnlineStatus(0)
}

func (x *UpdateStatusRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_service_controller_proto_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_controller_proto_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_service_controller_proto_controller_proto_rawDescGZIP(), []int{5}
}

var File_service_controller_proto_controller_proto protoreflect.FileDescriptor

const file_service_controller_proto_controller_proto_rawDesc = "" +
	"\n" +
	")service/controller/proto/controller.proto\x12\x10echat.controller\x1a\x13common/common.proto\"(\n" +
	"\x10AuthCheckRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"Z\n" +
	"\x11AuthCheckResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x86\x01\n" +
	"\x13RouteMessageRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x15\n" +
	"\x06msg_id\x18\x04 \x01(\tR\x05msgId\"\x80\x01\n" +
	"\x14RouteMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"{\n" +
	"\x13UpdateStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.common.OnlineStatusR\x06status\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId\"\x16\n" +
	"\x14UpdateStatusResponse2\xa7\x02\n" +
	"\x11ControllerService\x12T\n" +
	"\tAuthCheck\x12\".echat.controller.AuthCheckRequest\x1a#.echat.controller.AuthCheckResponse\x12]\n" +
	"\fRouteMessage\x12%.echat.controller.RouteMessageRequest\x1a&.echat.controller.RouteMessageResponse\x12]\n" +
	"\fUpdateStatus\x12%.echat.controller.UpdateStatusRequest\x1a&.echat.controller.UpdateStatusResponseB\x1fZ\x1dechat/service/controller/stubb\x06proto3"

var (
	file_service_controller_proto_controller_proto_rawDescOnce sync.Once
	file_service_controller_proto_controller_proto_rawDescData []byte
)

func file_service_controller_proto_controller_proto_rawDescGZIP() []byte {
	file_service_controller_proto_controller_proto_rawDescOnce.Do(func() {
		file_service_controller_proto_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_controller_proto_controller_proto_rawDesc), len(file_service_controller_proto_controller_proto_rawDesc)))
	})
	return file_service_controller_proto_controller_proto_rawDescData
}

var file_service_controller_proto_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_controller_proto_controller_proto_goTypes = []any{
	(*AuthCheckRequest)(nil),     // 0: echat.controller.AuthCheckRequest
	(*AuthCheckResponse)(nil),    // 1: echat.controller.AuthCheckResponse
	(*RouteMessageRequest)(nil),  // 2: echat.controller.RouteMessageRequest
	(*RouteMessageResponse)(nil), // 3: echat.controller.RouteMessageResponse
	(*UpdateStatusRequest)(nil),  // 4: echat.controller.UpdateStatusRequest
	(*UpdateStatusResponse)(nil), // 5: echat.controller.UpdateStatusResponse
	(common.OnlineStatus)(0),     // 6: common.OnlineStatus
}
var file_service_controller_proto_controller_proto_depIdxs = []int32{
	6, // 0: echat.controller.UpdateStatusRequest.status:type_name -> common.OnlineStatus
	0, // 1: echat.controller.ControllerService.AuthCheck:input_type -> echat.controller.AuthCheckRequest
	2, // 2: echat.controller.ControllerService.RouteMessage:input_type -> echat.controller.RouteMessageRequest
	4, // 3: echat.controller.ControllerService.UpdateStatus:input_type -> echat.controller.UpdateStatusRequest
	1, // 4: echat.controller.ControllerService.AuthCheck:output_type -> echat.controller.AuthCheckResponse
	3, // 5: echat.controller.ControllerService.RouteMessage:output_type -> echat.controller.RouteMessageResponse
	5, // 6: echat.controller.ControllerService.UpdateStatus:output_type -> echat.controller.UpdateStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_controller_proto_controller_proto_init() }
func file_service_controller_proto_controller_proto_init() {
	if File_service_controller_proto_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_controller_proto_controller_proto_rawDesc), len(file_service_controller_proto_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_controller_proto_controller_proto_goTypes,
		DependencyIndexes: file_service_controller_proto_controller_proto_depIdxs,
		MessageInfos:      file_service_controller_proto_controller_proto_msgTypes,
	}.Build()
	File_service_controller_proto_controller_proto = out.File
	file_service_controller_proto_controller_proto_goTypes = nil
	file_service_controller_proto_controller_proto_depIdxs = nil
}
