// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: service/gateway/proto/gateway.proto

package stub

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 目标用户
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                  // 消息 ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                           // 消息内容
	FromUserId    string                 `protobuf:"bytes,4,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 发送者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToUserRequest) Reset() {
	*x = PushToUserRequest{}
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserRequest) ProtoMessage() {}

func (x *PushToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserRequest.ProtoReflect.Descriptor instead.
func (*PushToUserRequest) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushToUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushToUserRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PushToUserRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushToUserRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

type PushToUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"` // 是否成功投递
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`        // 失败原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToUserResponse) Reset() {
	*x = PushToUserResponse{}
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserResponse) ProtoMessage() {}

func (x *PushToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserResponse.ProtoReflect.Descriptor instead.
func (*PushToUserResponse) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushToUserResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *PushToUserResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_service_gateway_proto_gateway_proto protoreflect.FileDescriptor

const file_service_gateway_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"#service/gateway/proto/gateway.proto\x12\rechat.gateway\"\x7f\n" +
	"\x11PushToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\ffrom_user_id\x18\x04 \x01(\tR\n" +
	"fromUserId\"J\n" +
	"\x12PushToUserResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2d\n" +
	"\x0fGatewayInternal\x12Q\n" +
	"\n" +
	"PushToUser\x12 .echat.gateway.PushToUserRequest\x1a!.echat.gateway.PushToUserResponseB\x1cZ\x1aechat/service/gateway/stubb\x06proto3"

var (
	file_service_gateway_proto_gateway_proto_rawDescOnce sync.Once
	file_service_gateway_proto_gateway_proto_rawDescData []byte
)

func file_service_gateway_proto_gateway_proto_rawDescGZIP() []byte {
	file_service_gateway_proto_gateway_proto_rawDescOnce.Do(func() {
		file_service_gateway_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_gateway_proto_gateway_proto_rawDesc), len(file_service_gateway_proto_gateway_proto_rawDesc)))
	})
	return file_service_gateway_proto_gateway_proto_rawDescData
}

var file_service_gateway_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_gateway_proto_gateway_proto_goTypes = []any{
	(*PushToUserRequest)(nil),  // 0: echat.gateway.PushToUserRequest
	(*PushToUserResponse)(nil), // 1: echat.gateway.PushToUserResponse
}
var file_service_gateway_proto_gateway_proto_depIdxs = []int32{
	0, // 0: echat.gateway.GatewayInternal.PushToUser:input_type -> echat.gateway.PushToUserRequest
	1, // 1: echat.gateway.GatewayInternal.PushToUser:output_type -> echat.gateway.PushToUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_gateway_proto_gateway_proto_init() }
func file_service_gateway_proto_gateway_proto_init() {
	if File_service_gateway_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_gateway_proto_gateway_proto_rawDesc), len(file_service_gateway_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_gateway_proto_gateway_proto_goTypes,
		DependencyIndexes: file_service_gateway_proto_gateway_proto_depIdxs,
		MessageInfos:      file_service_gateway_proto_gateway_proto_msgTypes,
	}.Build()
	File_service_gateway_proto_gateway_proto = out.File
	file_service_gateway_proto_gateway_proto_goTypes = nil
	file_service_gateway_proto_gateway_proto_depIdxs = nil
}
