// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: service/gateway/proto/gateway.proto

package stub

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// GatewayInternalService defines service.
type GatewayInternalService interface {
	// PushToUser Controller 推送消息给指定用户
	PushToUser(ctx context.Context, req *PushToUserRequest) (*PushToUserResponse, error)
}

func GatewayInternalService_PushToUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PushToUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GatewayInternalService).PushToUser(ctx, reqbody.(*PushToUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// GatewayInternalServer_ServiceDesc descriptor for server.RegisterService.
var GatewayInternalServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "echat.gateway.GatewayInternal",
	HandlerType: ((*GatewayInternalService)(nil)),
	Methods: []server.Method{
		{
			Name: "/echat.gateway.GatewayInternal/PushToUser",
			Func: GatewayInternalService_PushToUser_Handler,
		},
	},
}

// RegisterGatewayInternalService registers service.
func RegisterGatewayInternalService(s server.Service, svr GatewayInternalService) {
	if err := s.Register(&GatewayInternalServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("GatewayInternal register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedGatewayInternal struct{}

// PushToUser Controller 推送消息给指定用户
func (s *UnimplementedGatewayInternal) PushToUser(ctx context.Context, req *PushToUserRequest) (*PushToUserResponse, error) {
	return nil, errors.New("rpc PushToUser of service GatewayInternal is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// GatewayInternalClientProxy defines service client proxy
type GatewayInternalClientProxy interface {
	// PushToUser Controller 推送消息给指定用户
	PushToUser(ctx context.Context, req *PushToUserRequest, opts ...client.Option) (rsp *PushToUserResponse, err error)
}

type GatewayInternalClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewGatewayInternalClientProxy = func(opts ...client.Option) GatewayInternalClientProxy {
	return &GatewayInternalClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *GatewayInternalClientProxyImpl) PushToUser(ctx context.Context, req *PushToUserRequest, opts ...client.Option) (*PushToUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/echat.gateway.GatewayInternal/PushToUser")
	msg.WithCalleeServiceName(GatewayInternalServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("GatewayInternal")
	msg.WithCalleeMethod("PushToUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PushToUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
